# Generated by Django 5.0.3 on 2025-01-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('gaze_direction', models.CharField(max_length=50)),
                ('angle', models.FloatField()),
            ],
        ),
    ]
