# Generated by Django 5.0.3 on 2025-01-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaze',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gaze',
            name='gaze_direction',
            field=models.CharField(max_length=100),
        ),
    ]
