# Generated by Django 5.0.3 on 2025-01-27 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_gaze_message_alter_gaze_gaze_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaze',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
