# Generated by Django 5.0.3 on 2025-01-29 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0005_remove_gaze_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaze',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
