# Generated by Django 5.0.3 on 2025-01-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0006_gaze_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaze',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
